#include "airlockmanager.hpp"
#include "monitormanager.hpp"
#include "cursormanager.hpp"
#include "../caelestia/caelestiavars.hpp"
#include "../caelestia/astrahelmwriter.hpp"

#include <QFile>
#include <QDir>
#include <QProcess>
#include <QTemporaryFile>

namespace Helm::Managers {

static AirlockManager* s_instance = nullptr;

AirlockManager* AirlockManager::instance() {
    if (!s_instance) {
        s_instance = new AirlockManager();
    }
    return s_instance;
}

AirlockManager* AirlockManager::create(QQmlEngine*, QJSEngine*) {
    QQmlEngine::setObjectOwnership(instance(), QQmlEngine::CppOwnership);
    return instance();
}

AirlockManager::AirlockManager(QObject* parent)
    : QObject(parent)
{
    checkConfig();
}

bool AirlockManager::hasAirlockConfig() const {
    return m_hasAirlockConfig;
}

bool AirlockManager::isSyncing() const {
    return m_isSyncing;
}

QString AirlockManager::lastMessage() const {
    return m_lastMessage;
}

void AirlockManager::checkConfig() {
    bool exists = QFile::exists(QStringLiteral("/etc/greetd/hyprland.lua"));
    if (m_hasAirlockConfig != exists) {
        m_hasAirlockConfig = exists;
        emit configStatusChanged();
    }
}

QString AirlockManager::generateAirlockLua() const {
    const QString cursorTheme = CursorManager::instance()->currentTheme();
    const int cursorSize = CursorManager::instance()->currentSize();

    const bool disableTyping = Caelestia::CaelestiaVars::instance()->get(QStringLiteral("touchpadDisableTyping"), true).toBool();
    const double scrollFactor = Caelestia::CaelestiaVars::instance()->get(QStringLiteral("touchpadScrollFactor"), 0.3).toDouble();

    QString out;
    out += QStringLiteral("-- Generated by Astra Helm for Airlock (/etc/greetd/hyprland.lua)\n\n");

    // Monitors
    const QVariantList monitors = MonitorManager::instance()->liveMonitors();
    if (monitors.isEmpty()) {
        out += QStringLiteral("hl.monitor({ output = \"\", mode = \"preferred\", position = \"auto\", scale = 1 })\n\n");
    } else {
        for (const QVariant& mv : monitors) {
            const QVariantMap m = mv.toMap();
            if (m.value(QStringLiteral("disabled")).toBool()) {
                out += QStringLiteral("hl.monitor({ output = \"%1\", mode = \"disabled\" })\n").arg(m.value(QStringLiteral("name")).toString());
            } else {
                const QString modeStr = QStringLiteral("%1x%2@%3").arg(m.value(QStringLiteral("width")).toString(), m.value(QStringLiteral("height")).toString(), QString::number(m.value(QStringLiteral("refreshRate")).toDouble(), 'f', 2));
                const QString posStr = QStringLiteral("%1x%2").arg(m.value(QStringLiteral("x")).toString(), m.value(QStringLiteral("y")).toString());
                out += QStringLiteral("hl.monitor({ output = \"%1\", mode = \"%2\", position = \"%3\", scale = %4 })\n")
                    .arg(m.value(QStringLiteral("name")).toString(), modeStr, posStr, QString::number(m.value(QStringLiteral("scale")).toDouble()));
            }
        }
        out += QStringLiteral("\n");
    }

    // Default kiosk config
    out += QStringLiteral("hl.config({\n"
                          "  animations = { enabled = false },\n"
                          "  decoration = {\n"
                          "    blur = { enabled = false },\n"
                          "    shadow = { enabled = false },\n"
                          "  },\n"
                          "  input = {\n"
                          "    kb_layout = \"us\",\n"
                          "    numlock_by_default = false,\n"
                          "    repeat_delay = 250,\n"
                          "    repeat_rate = 35,\n"
                          "    touchpad = {\n"
                          "      natural_scroll = true,\n"
                          "      disable_while_typing = %1,\n"
                          "      scroll_factor = %2,\n"
                          "    },\n"
                          "  },\n"
                          "  misc = {\n"
                          "    disable_autoreload = true,\n"
                          "    disable_hyprland_logo = true,\n"
                          "    force_default_wallpaper = 0,\n"
                          "  },\n"
                          "})\n\n").arg(disableTyping ? QStringLiteral("true") : QStringLiteral("false"), QString::number(scrollFactor));

    // Cursors
    out += QStringLiteral("local cursor_theme = \"%1\"\n"
                          "local cursor_size = \"%2\"\n\n"
                          "hl.env(\"HYPRCURSOR_THEME\", cursor_theme)\n"
                          "hl.env(\"HYPRCURSOR_SIZE\", cursor_size)\n"
                          "hl.env(\"XCURSOR_THEME\", cursor_theme)\n"
                          "hl.env(\"XCURSOR_SIZE\", cursor_size)\n\n").arg(cursorTheme, QString::number(cursorSize));

    // Autostart greetd hook
    out += QStringLiteral("hl.on(\"hyprland.start\", function()\n"
                          "  hl.exec_cmd(\"astra-airlock; hyprctl dispatch exit\")\n"
                          "end)\n");

    return out;
}

bool AirlockManager::syncToAirlock() {
    m_isSyncing = true;
    emit syncingChanged();

    const QString content = generateAirlockLua();

    QTemporaryFile tempFile;
    if (!tempFile.open()) {
        m_isSyncing = false;
        m_lastMessage = QStringLiteral("Failed to create temporary file for sync.");
        emit syncingChanged();
        emit messageChanged();
        emit syncFinished(false, m_lastMessage);
        return false;
    }

    tempFile.write(content.toUtf8());
    tempFile.flush();
    const QString tempPath = tempFile.fileName();

    // Execute pkexec to copy the temporary file to /etc/greetd/hyprland.lua
    QProcess proc;
    QStringList args = {
        QStringLiteral("install"),
        QStringLiteral("-D"),
        QStringLiteral("-m"),
        QStringLiteral("0644"),
        tempPath,
        QStringLiteral("/etc/greetd/hyprland.lua")
    };

    proc.start(QStringLiteral("pkexec"), args);
    bool finished = proc.waitForFinished(30000);

    m_isSyncing = false;
    emit syncingChanged();

    if (finished && proc.exitCode() == 0) {
        m_hasAirlockConfig = true;
        m_lastMessage = QStringLiteral("Successfully synced Hyprland configuration to Airlock (/etc/greetd/hyprland.lua)!");
        emit configStatusChanged();
        emit messageChanged();
        emit syncFinished(true, m_lastMessage);
        return true;
    } else {
        const QString err = QString::fromUtf8(proc.readAllStandardError());
        m_lastMessage = err.isEmpty() ? QStringLiteral("Failed to authenticate or copy file via pkexec.") : err;
        emit messageChanged();
        emit syncFinished(false, m_lastMessage);
        return false;
    }
}

} // namespace Helm::Managers
