#include "airlockmanager.hpp"
#include "monitormanager.hpp"
#include "cursormanager.hpp"
#include "../caelestia/caelestiavars.hpp"
#include "../hyprland/hyprlandschema.hpp"

#include <QFile>
#include <QDir>
#include <QProcess>
#include <QTemporaryFile>

namespace FlightDeck::Managers {

static AirlockManager* s_instance = nullptr;

namespace {

struct AirlockSyncOption {
    const char* varKey;
    const char* hyprKey;
    QVariant fallback;
};

// Caelestia variable keys mirrored into the Airlock config. Values are read
// through CaelestiaVars::get() which resolves pending, saved and default values.
static const AirlockSyncOption kAirlockSyncOptions[] = {
    // Cursor & pointer
    { "cursorEnableHyprcursor", "cursor:enable_hyprcursor", true },
    { "cursorNoWarps", "cursor:no_warps", false },
    { "cursorPersistentWarps", "cursor:persistent_warps", false },
    { "cursorZoomFactor", "cursor:zoom_factor", 1.0 },
    { "cursorInactiveTimeout", "cursor:inactive_timeout", 0 },
    { "cursorHideOnKeyPress", "cursor:hide_on_key_press", false },
    { "cursorHideOnTouch", "cursor:hide_on_touch", false },
    { "cursorHideOnTablet", "cursor:hide_on_tablet", false },

    // Input devices - Keyboard
    { "kbLayout", "input:kb_layout", "us" },
    { "kbVariant", "input:kb_variant", QString() },
    { "kbOptions", "input:kb_options", QString() },
    { "numlockByDefault", "input:numlock_by_default", false },
    { "keyRepeatRate", "input:repeat_rate", 25 },
    { "keyRepeatDelay", "input:repeat_delay", 600 },

    // Input devices - Mouse & pointer
    { "mouseSensitivity", "input:sensitivity", 0.0 },
    { "mouseAccelProfile", "input:accel_profile", QString() },
    { "mouseNaturalScroll", "input:natural_scroll", false },
    { "mouseScrollFactor", "input:scroll_factor", 1.0 },
    { "leftHandedMode", "input:left_handed", false },
    { "followMouse", "input:follow_mouse", 1 },
    { "mouseRefocus", "input:mouse_refocus", false },
    { "floatSwitchOverrideFocus", "input:float_switch_override_focus", 1 },

    // Input devices - Touchpad
    { "touchpadDisableTyping", "input:touchpad:disable_while_typing", true },
    { "touchpadTapToClick", "input:touchpad:tap-to-click", true },
    { "touchpadClickfingerBehavior", "input:touchpad:clickfinger_behavior", false },
    { "touchpadMiddleButtonEmulation", "input:touchpad:middle_button_emulation", false },
    { "touchpadScrollFactor", "input:touchpad:scroll_factor", 0.3 },

    // Gestures - Workspace swipe
    { "workspaceSwipeCreateNew", "gestures:workspace_swipe_create_new", true },
    { "workspaceSwipeForever", "gestures:workspace_swipe_forever", false },
    { "workspaceSwipeCancelRatio", "gestures:workspace_swipe_cancel_ratio", 0.5 },
    { "workspaceSwipeFingers", "gestures:workspace_swipe_fingers", 4 },
    { "workspaceSwipeDistance", "gestures:workspace_swipe_distance", 300 },
    { "workspaceSwipeInvert", "gestures:workspace_swipe_invert", false },
};

} // namespace

AirlockManager* AirlockManager::instance() {
    if (!s_instance) {
        s_instance = new AirlockManager();
    }
    return s_instance;
}

AirlockManager* AirlockManager::create(QQmlEngine*, QJSEngine*) {
    QQmlEngine::setObjectOwnership(instance(), QQmlEngine::CppOwnership);
    return instance();
}

AirlockManager::AirlockManager(QObject* parent)
    : QObject(parent)
{
    checkConfig();
}

bool AirlockManager::hasAirlockConfig() const {
    return m_hasAirlockConfig;
}

bool AirlockManager::isSyncing() const {
    return m_isSyncing;
}

QString AirlockManager::lastMessage() const {
    return m_lastMessage;
}

void AirlockManager::checkConfig() {
    bool exists = QFile::exists(QStringLiteral("/etc/greetd/hyprland.lua"));
    if (m_hasAirlockConfig != exists) {
        m_hasAirlockConfig = exists;
        emit configStatusChanged();
    }
}

QString AirlockManager::generateAirlockLua() const {
    // Airlock runs its own Hyprland session and has no access to Caelestia
    // variables at runtime, so every setting from the Cursor & pointer, Input
    // devices and Displays & monitors pages is baked in as a concrete value.
    auto* const vars = Caelestia::CaelestiaVars::instance();
    const QString cursorTheme = CursorManager::instance()->currentTheme();
    const int cursorSize = CursorManager::instance()->currentSize();

    const bool hyprcursorEnabled = vars->get(QStringLiteral("cursorEnableHyprcursor"), true).toBool();
    const bool noHardwareCursors = vars->get(QStringLiteral("cursorNoHardwareCursors"), false).toBool();

    QString out;
    out += QStringLiteral("-- Generated by FlightDeck for Airlock (/etc/greetd/hyprland.lua)\n\n");

    // Display: monitors
    const QVariantList monitors = MonitorManager::instance()->liveMonitors();
    if (monitors.isEmpty()) {
        out += QStringLiteral("hl.monitor({ output = \"\", mode = \"preferred\", position = \"auto\", scale = 1 })\n\n");
    } else {
        for (const QVariant& mv : monitors) {
            const QVariantMap m = mv.toMap();
            if (m.value(QStringLiteral("disabled")).toBool()) {
                out += QStringLiteral("hl.monitor({ output = \"%1\", mode = \"disabled\" })\n").arg(m.value(QStringLiteral("name")).toString());
            } else {
                const QString modeStr = QStringLiteral("%1x%2@%3").arg(m.value(QStringLiteral("width")).toString(), m.value(QStringLiteral("height")).toString(), QString::number(m.value(QStringLiteral("refreshRate")).toDouble(), 'f', 2));
                const QString posStr = QStringLiteral("%1x%2").arg(m.value(QStringLiteral("x")).toString(), m.value(QStringLiteral("y")).toString());
                out += QStringLiteral("hl.monitor({ output = \"%1\", mode = \"%2\", position = \"%3\", scale = %4, transform = %5 })\n")
                    .arg(m.value(QStringLiteral("name")).toString(), modeStr, posStr,
                         QString::number(m.value(QStringLiteral("scale")).toDouble()),
                         m.value(QStringLiteral("transform")).toString());
            }
        }
        out += QStringLiteral("\n");
    }

    // Cursors: Hyprcursor & Xcursor environment
    if (hyprcursorEnabled) {
        out += QStringLiteral("hl.env(\"HYPRCURSOR_THEME\", \"%1\")\n").arg(cursorTheme);
        out += QStringLiteral("hl.env(\"HYPRCURSOR_SIZE\", %1)\n").arg(QString::number(cursorSize));
    }
    out += QStringLiteral("hl.env(\"XCURSOR_THEME\", \"%1\")\n"
                          "hl.env(\"XCURSOR_SIZE\", %2)\n").arg(cursorTheme, QString::number(cursorSize));
    if (noHardwareCursors) {
        out += QStringLiteral("hl.env(\"WLR_NO_HARDWARE_CURSORS\", \"1\")\n");
    }
    out += QStringLiteral("\n");

    // Cursor, input & gesture settings baked from Caelestia variables
    QVariantMap nativeOptions;
    for (const AirlockSyncOption& opt : kAirlockSyncOptions) {
        nativeOptions.insert(QLatin1String(opt.hyprKey), vars->get(QLatin1String(opt.varKey), opt.fallback));
    }
    out += FlightDeck::Hyprland::HyprlandSchema::instance()->serializeToLuaConfig(nativeOptions);
    out += QStringLiteral("\n");

    // Autostart greetd hook
    out += QStringLiteral("hl.on(\"hyprland.start\", function()\n"
                          "  hl.exec_cmd(\"astra-airlock; hyprctl dispatch exit\")\n"
                          "end)\n");

    return out;
}

bool AirlockManager::syncToAirlock() {
    m_isSyncing = true;
    emit syncingChanged();

    const QString content = generateAirlockLua();

    QTemporaryFile tempFile;
    if (!tempFile.open()) {
        m_isSyncing = false;
        m_lastMessage = QStringLiteral("Failed to create temporary file for sync.");
        emit syncingChanged();
        emit messageChanged();
        emit syncFinished(false, m_lastMessage);
        return false;
    }

    tempFile.write(content.toUtf8());
    tempFile.flush();
    const QString tempPath = tempFile.fileName();

    // Execute pkexec to copy the temporary file to /etc/greetd/hyprland.lua
    QProcess proc;
    QStringList args = {
        QStringLiteral("install"),
        QStringLiteral("-D"),
        QStringLiteral("-m"),
        QStringLiteral("0644"),
        tempPath,
        QStringLiteral("/etc/greetd/hyprland.lua")
    };

    proc.start(QStringLiteral("pkexec"), args);
    bool finished = proc.waitForFinished(30000);

    m_isSyncing = false;
    emit syncingChanged();

    if (finished && proc.exitCode() == 0) {
        m_hasAirlockConfig = true;
        m_lastMessage = QStringLiteral("Successfully synced Hyprland configuration to Airlock (/etc/greetd/hyprland.lua)!");
        emit configStatusChanged();
        emit messageChanged();
        emit syncFinished(true, m_lastMessage);
        return true;
    } else {
        const QString err = QString::fromUtf8(proc.readAllStandardError());
        m_lastMessage = err.isEmpty() ? QStringLiteral("Failed to authenticate or copy file via pkexec.") : err;
        emit messageChanged();
        emit syncFinished(false, m_lastMessage);
        return false;
    }
}

} // namespace FlightDeck::Managers
