#include "caelestiabootstrap.hpp"
#include "astrahelmwriter.hpp"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QDebug>

namespace Helm::Caelestia {

void CaelestiaBootstrap::ensureAstraHelmSourced() {
    const QString userLuaPath = QDir::homePath() + QStringLiteral("/.config/caelestia/hypr-user.lua");
    const QString helmPath = AstraHelmWriter::astraHelmFilePath();

    // Ensure astra-helm.lua exists with minimal header if missing
    if (!QFile::exists(helmPath)) {
        const QFileInfo fi(helmPath);
        if (!fi.dir().exists()) {
            fi.dir().mkpath(QStringLiteral("."));
        }
        QFile helmFile(helmPath);
        if (helmFile.open(QIODevice::WriteOnly | QIODevice::Text)) {
            helmFile.write("-- Generated by Astra Helm\n\n");
            helmFile.close();
        }
    }

    QFile file(userLuaPath);
    if (!file.exists()) {
        const QFileInfo fi(userLuaPath);
        if (!fi.dir().exists()) {
            fi.dir().mkpath(QStringLiteral("."));
        }
        if (file.open(QIODevice::WriteOnly | QIODevice::Text)) {
            file.write("-- Caelestia user configuration\n\n-- Astra Helm managed settings\ndofile(os.getenv(\"HOME\") .. \"/.config/caelestia/astra-helm.lua\")\n");
            file.close();
        }
        return;
    }

    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return;
    }

    const QString content = QString::fromUtf8(file.readAll());
    file.close();

    if (content.contains(QStringLiteral("astra-helm.lua"))) {
        return; // Already sourced!
    }

    // Append one-time sourcing block
    if (file.open(QIODevice::Append | QIODevice::Text)) {
        file.write("\n-- Astra Helm managed settings\ndofile(os.getenv(\"HOME\") .. \"/.config/caelestia/astra-helm.lua\")\n");
        file.close();
        qInfo() << "CaelestiaBootstrap: Added astra-helm.lua sourcing to hypr-user.lua";
    }
}

} // namespace Helm::Caelestia
