#include "caelestiabootstrap.hpp"
#include "flightdeckwriter.hpp"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QDebug>

namespace FlightDeck::Caelestia {

void CaelestiaBootstrap::ensureFlightDeckSourced() {
    const QString userLuaPath = QDir::homePath() + QStringLiteral("/.config/caelestia/hypr-user.lua");
    const QString flightDeckPath = FlightDeckWriter::flightDeckFilePath();
    const QString fileName = QFileInfo(flightDeckPath).fileName();

    // Ensure flightdeck lua file exists with minimal header if missing
    if (!QFile::exists(flightDeckPath)) {
        const QFileInfo fi(flightDeckPath);
        if (!fi.dir().exists()) {
            fi.dir().mkpath(QStringLiteral("."));
        }
        QFile fdFile(flightDeckPath);
        if (fdFile.open(QIODevice::WriteOnly | QIODevice::Text)) {
            fdFile.write("-- Generated by FlightDeck\n\n");
            fdFile.close();
        }
    }

    QFile file(userLuaPath);
    if (!file.exists()) {
        const QFileInfo fi(userLuaPath);
        if (!fi.dir().exists()) {
            fi.dir().mkpath(QStringLiteral("."));
        }
        if (file.open(QIODevice::WriteOnly | QIODevice::Text)) {
            file.write(QStringLiteral("-- Caelestia user configuration\n\n-- FlightDeck managed settings\ndofile(os.getenv(\"HOME\") .. \"/.config/caelestia/%1\")\n").arg(fileName).toUtf8());
            file.close();
        }
        return;
    }

    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return;
    }

    const QString content = QString::fromUtf8(file.readAll());
    file.close();

    if (content.contains(fileName) || content.contains(QStringLiteral("astra-flightdeck.lua"))) {
        return; // Already sourced!
    }

    // Append one-time sourcing block
    if (file.open(QIODevice::Append | QIODevice::Text)) {
        file.write(QStringLiteral("\n-- FlightDeck managed settings\ndofile(os.getenv(\"HOME\") .. \"/.config/caelestia/%1\")\n").arg(fileName).toUtf8());
        file.close();
        qInfo() << "CaelestiaBootstrap: Added" << fileName << "sourcing to hypr-user.lua";
    }
}

} // namespace FlightDeck::Caelestia
